apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --out helm-from-kompose -f docker-compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: chainlit
  name: chainlit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chainlit
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --out helm-from-kompose -f docker-compose.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: chainlit
    spec:
      containers:
        - image: chainlit
          name: chainlit
          volumeMounts:
            - mountPath: /run/secrets
              name: openai-api-key
              subPath: openai-api-key
            - mountPath: /run/secrets
              name: tavily-api-key
              subPath: tavily-api-key
      restartPolicy: Always
      volumes:
        - name: openai-api-key
          secret:
            items:
              - key: openai-api-key
                path: openai-api-key
            secretName: openai-api-key
        - name: tavily-api-key
          secret:
            items:
              - key: tavily-api-key
                path: tavily-api-key
            secretName: tavily-api-key
